"""empty message

Revision ID: 698119de7a2f
Revises: d58849ab21c4
Create Date: 2023-05-17 03:19:40.400613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698119de7a2f'
down_revision = 'd58849ab21c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('users_from_id', sa.Integer(), nullable=False),
    sa.Column('users_to_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['users_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['users_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
