"""empty message

Revision ID: c0a067817f16
Revises: 6b4edd576ede
Create Date: 2023-05-20 19:19:44.907061

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0a067817f16'
down_revision = '6b4edd576ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('github')
        batch_op.drop_column('linkedin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('linkedin', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('github', mysql.VARCHAR(length=100), nullable=True))

    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('users_from_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('users_to_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['users_from_id'], ['users.id'], name='messages_ibfk_1'),
    sa.ForeignKeyConstraint(['users_to_id'], ['users.id'], name='messages_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
